# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - run: javac -d ./out/ ./src/printserver/*.java ./src/printserver/permissions/*.java ./src/printserver/actions/*.java ./src/printserver/modules/*.java ./src/printserver/principals/*.java ./src/printserver/server/*.java
    - run: jar -cvf PrintServer.jar -c /out/printserver/PrintServer.class
    - run: jar -cvf PrintServerLoginModule.jar -c /out/printserver/modules/PrintServerLoginModule.class
    - run: jar -cvf PrintServerActions.jar sample/module/SampleLoginModule.class sample/principal/SamplePrincipal.class
