name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - run: mkdir out
    - run: javac -d ./out/ ./src/printserver/*.java ./src/printserver/permissions/*.java ./src/printserver/actions/*.java ./src/printserver/modules/*.java ./src/printserver/principals/*.java ./src/printserver/server/*.java
    - run: jar -cvf PrintServer.jar ./out/printserver/Main.class ./out/printserver/PrintServerCallbackHandler.class
    - run: jar -cvf PrintServerLoginModule.jar ./out/printserver/modules/PrintServerLoginModule.class -C ./out/printserver/principals/ .
    - run: jar -cvf PrintServerActions.jar -C ./out/printserver/actions/ .
